# ============================================================================= 
# @file    config.yml
# @authors Derek Anderson (derek.murphy.anderson@protonmail.com)
# -----------------------------------------------------------------------------
# @brief Snakemake config. Defines global parameters that
#   can be overwritten at runtime. 
# =============================================================================

# name of generated output datacard
card_name:
  "output.yml"

# template datacard for output
template:
  "template.yml"

# name of list to dump input
# files into
input_list:
  "run/input.list"

# name of snakemake file
# to dump rules into
rules_file:
  "run/rules.smk"

# name of snakemake config
# to dump constants into
config_file:
  "run/rules.yml"
